sudo: false
language: node_js
node_js:
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '10'
before_install:
  - npm install -g npm@latest
  - npm install -g mocha
install:
  - npm install
script: npm run test:all
cache: npm